version: '3.8'

services:
  converter_django:
    container_name: converter_django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/
    ports:
      - 8000:8000
    env_file:
      - .env
